version: "2"
services:

  influxdb:
    build:
      context: ./
      dockerfile: influxdb/Dockerfile
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - "INFLUXDB_DB=grafana"
      - "INFLUXDB_USER=grafana"
      - "INFLUXDB_PASS=grafana"

  grafana:
    image: grafana/grafana
    ports:
      - "9000:3000"
    depends_on:
      - influxdb
    volumes:
      - "./grafana:/var/lib/grafana"

  alerts:
    build:
      context: ./
      dockerfile: alerts/Dockerfile
    ports:
      - "9450:9450"
    environment:
      - "SERVER_PORT=9450"
      - "SERVER_DOMAIN=10.0.0.10"
      - "SEND_ADDRESS=mr.zacharycotton@gmail.com"
      - "SEND_ADDRESS_PASSWORD=#rtf%utn00bx"
      - "RECV_ADDRESS=mr.zacharycotton@gmail.com"
      - "TZ=America/Los_Angeles"

  # ============== SENSORS =================

  router_connectivity:
    build:
      context: ./
      dockerfile: sensors/link_connectivity/Dockerfile
    depends_on:
      - influxdb
    environment:
      - "INFLUXDB_DB=grafana"
      - "INFLUXDB_USER=grafana"
      - "INFLUXDB_PASS=grafana"
      - "INFLUXDB_HOST=influxdb"
      - "INFLUXDB_PORT=8086"
      - "LINK_TO=10.0.0.1"

  cups_queue_size:
    build:
      context: ./
      dockerfile: sensors/cups_queue_size/Dockerfile
    depends_on:
      - influxdb
    environment:
      - "INFLUXDB_DB=grafana"
      - "INFLUXDB_USER=grafana"
      - "INFLUXDB_PASS=grafana"
      - "INFLUXDB_HOST=influxdb"
      - "INFLUXDB_PORT=8086"
      - "CUPS_HOST=10.0.0.10"
      - "CUPS_PORT=631"

  cups_up:
    build:
      context: ./
      dockerfile: sensors/server_up/Dockerfile
    depends_on:
      - influxdb
    environment:
      - "INFLUXDB_DB=grafana"
      - "INFLUXDB_USER=grafana"
      - "INFLUXDB_PASS=grafana"
      - "INFLUXDB_HOST=influxdb"
      - "INFLUXDB_PORT=8086"
      - "SERVER_URL=http://10.0.0.10:631/printers"
