#!/bin/bash

sleep 2

INFLUXDB_HOST="127.0.0.1"
INFLUXDB_PORT="8086"
INFLUXDB_CMD="influx -host $INFLUXDB_HOST -port $INFLUXDB_PORT -execute"

INFLUXDB_CMD_DB="influx -host $INFLUXDB_HOST -port $INFLUXDB_PORT -database $INFLUXDB_DB -execute"

$INFLUXDB_CMD "CREATE DATABASE $INFLUXDB_DB"
$INFLUXDB_CMD_DB "CREATE USER $INFLUXDB_USER WITH PASSWORD '$INFLUXDB_PASS' WITH ALL PRIVILEGES"
